name: Publish Documentation
on:
  push:
    branches:
      - ya-dev-test

jobs:
  publish:
    name: Publish Dev Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Tools
        run: |
          pip install awscli
      - name: Build Docs
        run: |
          yarn
          yarn build
          yarn release
          cp website/build/botpress-docs/index.html website/build/botpress-docs/docs/index.html
      - name: Commit Versioned Docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Versioned Docs
