name: Publish Documentation
on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Publish Dev Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.13.0'
      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install Tools
        run: |
          pip install awscli

      - name: Build Docs
        run: |
          yarn
          yarn build
          cp website/build/botpress-docs/index.html website/build/botpress-docs/docs/index.html

      - name: Version Docs
        run: yarn version-docs

      - name: Commit Versioned Docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit Versioned Docs

      - name: Publish Docs
        env:
          DEV_DOCS_BUCKET_NAME: ${{ secrets.DEV_DOCS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync website/build/botpress-docs s3://$DEV_DOCS_BUCKET_NAME/ --delete
